# this service should be run in the letsencrypt.gearstain cluster
services:
  certbot-dns-namecheap:
    build:
       context: .
       args:                                                                     
         - CERTBOT_TAG=arm64v8-latest
    volumes:
      - ./out/certs:/etc/letsencrypt
      - ./out/logs:/var/log/letsencrypt
      - ./namecheap.ini:/namecheap.ini
  
